import {
  type DeletionOperation,
  type DeletionPreview,
  DeletionPreviewSchema,
} from "@workspace/contracts";
import type { Database } from "@workspace/contracts/database";

import type { SupabaseClient } from "@supabase/supabase-js";

import {
  createSupabaseAdminClient,
  DOCUMENT_BUCKET,
} from "./document-service-support.js";

export interface DeletionService {
  preview(
    ownerId: string,
    targetType: "application" | "document",
    targetId: string,
  ): Promise<DeletionPreview>;
  delete(
    ownerId: string,
    targetType: "application" | "document",
    targetId: string,
    fingerprint: string,
  ): Promise<DeletionOperation>;
  get(ownerId: string, operationId: string): Promise<DeletionOperation>;
  cleanup(ownerId: string): Promise<void>;
  isMaintenance(ownerId: string): Promise<boolean>;
}
export class DeletionServiceError extends Error {
  constructor(readonly reason: string) {
    super(reason);
  }
}
type OperationRow =
  Database["public"]["Tables"]["career_deletion_operations"]["Row"];
function operation(row: OperationRow): DeletionOperation {
  return {
    id: row.id,
    targetType: row.target_type as DeletionOperation["targetType"],
    targetId: row.target_id,
    status: row.status as DeletionOperation["status"],
    error: row.error,
    createdAt: row.created_at,
    completedAt: row.completed_at,
  };
}
function failure(error: { message: string }): never {
  const reason =
    [
      "resource_not_found",
      "deletion_preview_changed",
      "deletion_blocked",
      "career_ops_maintenance",
    ].find((value) => error.message.includes(value)) ?? "unavailable";
  throw new DeletionServiceError(reason);
}
export class SupabaseDeletionService implements DeletionService {
  constructor(private readonly supabase: SupabaseClient<Database>) {}
  async isMaintenance(ownerId: string) {
    const { data, error } = await this.supabase
      .from("career_ops_maintenance")
      .select("enabled")
      .eq("owner_id", ownerId)
      .maybeSingle();
    if (error) failure(error);
    return data?.enabled ?? false;
  }
  async preview(
    ownerId: string,
    targetType: "application" | "document",
    targetId: string,
  ) {
    const { data, error } = await this.supabase.rpc("preview_career_deletion", {
      p_owner_id: ownerId,
      p_target_type: targetType,
      p_target_id: targetId,
    });
    if (error) failure(error);
    return DeletionPreviewSchema.parse(data);
  }
  async delete(
    ownerId: string,
    targetType: "application" | "document",
    targetId: string,
    fingerprint: string,
  ) {
    const { data, error } = await this.supabase.rpc("delete_career_resource", {
      p_owner_id: ownerId,
      p_target_type: targetType,
      p_target_id: targetId,
      p_fingerprint: fingerprint,
    });
    if (error) failure(error);
    return operation(data);
  }
  async get(ownerId: string, operationId: string) {
    const { data, error } = await this.supabase
      .from("career_deletion_operations")
      .select("*")
      .eq("owner_id", ownerId)
      .eq("id", operationId)
      .maybeSingle();
    if (error) failure(error);
    if (!data) throw new DeletionServiceError("resource_not_found");
    return operation(data);
  }
  async cleanup(ownerId: string) {
    const { data, error } = await this.supabase.rpc(
      "claim_career_storage_cleanup",
      { p_owner_id: ownerId, p_limit: 20 },
    );
    if (error) failure(error);
    for (const task of data) {
      // Paths are generated by the purge RPC; never delete a prefix supplied by a client.
      if (!task.storage_path.startsWith(`${ownerId}/`))
        throw new DeletionServiceError("invalid_storage_path");
      const { error: storageError } = await this.supabase.storage
        .from(DOCUMENT_BUCKET)
        .remove([task.storage_path]);
      const { error: finishError } = await this.supabase.rpc(
        "finish_career_storage_cleanup",
        {
          p_owner_id: ownerId,
          p_cleanup_id: task.id,
          p_attempt: task.attempts,
          p_success: !storageError,
        },
      );
      if (finishError) failure(finishError);
    }
  }
}
export function createDeletionService(
  env: CloudflareBindings,
): DeletionService {
  return new SupabaseDeletionService(createSupabaseAdminClient(env));
}
